version: "3.7"

services:
  server:
    container_name: server
    build:
      context: server/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/server
    env_file: server/.env
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: jewlere

  mysql:
    image: mysql:5.7
    container_name: mysql_dev
    volumes:
      - jewlere-dev-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: jewlere

  client:
    build:
      context: client/
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "3000:3000"
    volumes:
      - ./:/client

volumes:
  jewlere-dev-data:
